"use client";
import { useState } from "react";
import useSWR, { mutate } from "swr";
import { api, ApiError, fetcher } from "@/lib/api";
import { cn } from "@/lib/cn";
import { useDialog } from "./dialog-provider";
import { useT } from "@/lib/i18n";
import {
  AlertTriangle,
  ChevronDown,
  ChevronRight,
  Download,
  RefreshCw,
  Trash2,
} from "lucide-react";

type CrashSummary = {
  name: string;
  size: number;
  mtime: string;
  kind: "mc" | "jvm";
  time?: string;
  description?: string;
  exception?: string;
  suspectPackages: string[];
};

type CrashDetail = CrashSummary & {
  content: string;
  summary: {
    time?: string;
    description?: string;
    exception?: string;
    suspectPackages: string[];
  };
};

export function ServerDiagnostics({
  serverId,
}: {
  serverId: string;
}): JSX.Element {
  const { data, isLoading } = useSWR<{ reports: CrashSummary[] }>(
    `/servers/${serverId}/crash-reports`,
    fetcher,
    { refreshInterval: 20000, shouldRetryOnError: false }
  );

  const reports = data?.reports ?? [];

  return (
    <section className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="heading-md">Crash reports</h3>
          <p className="text-sm text-ink-muted mt-1">
            Generated by the game when the server throws an uncaught error.
            Stored in <code className="kbd">/data/crash-reports</code> and
            JVM <code className="kbd">hs_err_pid*.log</code> files at the root.
          </p>
        </div>
        <button
          className="btn btn-ghost !py-1.5 !px-2"
          onClick={() => mutate(`/servers/${serverId}/crash-reports`)}
          aria-label="Refresh"
          title="Refresh"
        >
          <RefreshCw size={14} />
        </button>
      </div>

      {isLoading ? (
        <div className="tile p-8 text-center text-ink-muted">Loading…</div>
      ) : reports.length === 0 ? (
        <div className="tile p-10 text-center">
          <p className="text-sm text-ink-muted">
            No crash reports. The server hasn't crashed — or someone already
            cleaned them up.
          </p>
        </div>
      ) : (
        <ul className="space-y-3">
          {reports.map((r) => (
            <CrashRow key={r.name} serverId={serverId} report={r} />
          ))}
        </ul>
      )}
    </section>
  );
}

function CrashRow({
  serverId,
  report,
}: {
  serverId: string;
  report: CrashSummary;
}): JSX.Element {
  const dialog = useDialog();
  const { t } = useT();
  const [open, setOpen] = useState(false);
  const [detail, setDetail] = useState<CrashDetail | null>(null);
  const [loading, setLoading] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  async function toggle(): Promise<void> {
    if (open) {
      setOpen(false);
      return;
    }
    setOpen(true);
    if (detail) return;
    setLoading(true);
    setErr(null);
    try {
      const res = await api.get<CrashDetail>(
        `/servers/${serverId}/crash-reports/${encodeURIComponent(report.name)}`
      );
      setDetail(res);
    } catch (e) {
      setErr(e instanceof ApiError ? e.message : String(e));
    } finally {
      setLoading(false);
    }
  }

  async function remove(): Promise<void> {
    const ok = await dialog.confirm({
      tone: "danger",
      danger: true,
      title: t("diagnostics.deleteConfirm.title"),
      message: t("diagnostics.deleteConfirm.body", { name: report.name }),
      okLabel: t("common.delete"),
    });
    if (!ok) return;
    try {
      await api.del(
        `/servers/${serverId}/crash-reports/${encodeURIComponent(report.name)}`
      );
      mutate(`/servers/${serverId}/crash-reports`);
    } catch (e) {
      dialog.alert({
        tone: "danger",
        title: t("common.error"),
        message: e instanceof ApiError ? e.message : String(e),
      });
    }
  }

  function download(): void {
    if (!detail) return;
    const blob = new Blob([detail.content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = report.name;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <li className="tile overflow-hidden">
      <button
        type="button"
        className="w-full flex items-center gap-3 p-4 text-left hover:bg-surface-2 transition-colors"
        onClick={toggle}
      >
        <span
          className={cn(
            "w-8 h-8 rounded-md grid place-items-center shrink-0",
            report.kind === "jvm"
              ? "bg-[rgb(var(--danger-soft))] text-[rgb(var(--danger))]"
              : "bg-[rgb(var(--warning-soft))] text-[rgb(var(--warning))]"
          )}
        >
          <AlertTriangle size={15} />
        </span>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-mono text-xs truncate">{report.name}</span>
            <span className="chip chip-muted text-[10px]">
              {report.kind === "jvm" ? "JVM crash" : "MC crash"}
            </span>
          </div>
          {report.exception && (
            <div className="text-sm text-ink mt-1 line-clamp-2">
              {report.exception}
            </div>
          )}
          <div className="text-[11px] text-ink-muted mt-1 flex items-center gap-3 flex-wrap">
            <span>{new Date(report.mtime).toLocaleString()}</span>
            <span className="tabular-nums">{formatSize(report.size)}</span>
            {report.suspectPackages.length > 0 && (
              <span className="truncate">
                suspects:{" "}
                <span className="font-mono">
                  {report.suspectPackages.slice(0, 3).join(", ")}
                  {report.suspectPackages.length > 3
                    ? ` +${report.suspectPackages.length - 3}`
                    : ""}
                </span>
              </span>
            )}
          </div>
        </div>
        {open ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
      </button>

      {open && (
        <div className="border-t border-line p-4 space-y-3">
          {loading && (
            <div className="text-sm text-ink-muted">Loading report…</div>
          )}
          {err && (
            <div className="text-sm text-[rgb(var(--danger))]">{err}</div>
          )}
          {detail && (
            <>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
                {detail.summary.time && (
                  <MetaRow label="Time">{detail.summary.time}</MetaRow>
                )}
                {detail.summary.description && (
                  <MetaRow label="Description">
                    {detail.summary.description}
                  </MetaRow>
                )}
                {detail.summary.exception && (
                  <MetaRow label="Exception" full>
                    <code className="text-[rgb(var(--danger))]">
                      {detail.summary.exception}
                    </code>
                  </MetaRow>
                )}
                {detail.summary.suspectPackages.length > 0 && (
                  <MetaRow label="Suspect packages" full>
                    <div className="flex flex-wrap gap-1.5 mt-1">
                      {detail.summary.suspectPackages.map((p) => (
                        <span
                          key={p}
                          className="chip chip-muted font-mono text-[11px]"
                        >
                          {p}
                        </span>
                      ))}
                    </div>
                  </MetaRow>
                )}
              </div>

              <div className="flex items-center gap-2">
                <button className="btn btn-ghost" onClick={download}>
                  <Download size={14} /> Download
                </button>
                <button className="btn btn-danger" onClick={remove}>
                  <Trash2 size={14} /> Delete
                </button>
              </div>

              <details className="tile p-3 bg-surface-2">
                <summary className="text-sm cursor-pointer select-none text-ink-secondary">
                  Full report
                </summary>
                <pre className="mt-3 text-[11px] font-mono whitespace-pre-wrap break-all max-h-[60vh] overflow-auto">
                  {detail.content}
                </pre>
              </details>
            </>
          )}
        </div>
      )}
    </li>
  );
}

function MetaRow({
  label,
  children,
  full,
}: {
  label: string;
  children: React.ReactNode;
  full?: boolean;
}): JSX.Element {
  return (
    <div className={full ? "md:col-span-2" : undefined}>
      <div className="text-[10px] uppercase tracking-wider text-ink-muted">
        {label}
      </div>
      <div className="mt-0.5">{children}</div>
    </div>
  );
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}
