import type { FastifyInstance } from "fastify";
import { prisma } from "../db.js";
import { streamMrpack } from "./export-mrpack.js";

/**
 * Unauthenticated client-pack download. Mounted at root under /p/.
 * The token is a 32-hex-char value generated by the server-edit
 * endpoint (server.routes.ts /:id/public-pack-token POST). Friends
 * paste the URL straight into Prism / Modrinth App / ATLauncher and
 * get the full client pack — no panel account, no login.
 *
 * Friendly URL shape: /p/<token>.mrpack — both the path component
 * and the trailing .mrpack are mandatory so launchers that sniff
 * extensions detect it as a Modrinth pack.
 */
export async function publicPackRoutes(app: FastifyInstance): Promise<void> {
  app.get("/p/:tokenWithExt", async (req, reply) => {
    const { tokenWithExt } = req.params as { tokenWithExt: string };
    const m = /^([a-f0-9]{32})\.mrpack$/i.exec(tokenWithExt);
    if (!m) {
      reply.code(404);
      return { error: "Not found" };
    }
    const token = m[1]!.toLowerCase();
    const server = await prisma.server.findUnique({
      where: { publicPackToken: token },
    });
    if (!server) {
      reply.code(404);
      return { error: "Not found" };
    }
    const node = await prisma.node.findUniqueOrThrow({
      where: { id: server.nodeId },
    });
    return streamMrpack(server, node, reply, { includeAutoDetected: true });
  });
}
